version: '3.9'

services:
  todo_db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    env_file:
      - /.env
    ports:
      - 5432:5432
    volumes:
      - budget_db:/var/lib/postgresql/data

volumes:
  budget_db:
